### ISSUE TITLE
Query: "WHERE IN(<array>)"

### ISSUE THREAD

**Issue by mixartemev** [CircuitSacul/DetaORM#8]
I need to use IN operator in query, is it possible?

**Comment by circuitsacul** [comment]
You can use `Field.contains`, which works on strings and arrays.

```py
user = await User.where(User.usernane.contains("somestring"))
```

**Comment by mixartemev** [comment]
I need query like a:
`SELECT * FROM users WHERE username IN ('vasya', 'petya', 'misha');`

**Comment by circuitsacul** [comment]
You can OR multiple queries to achieve that:
```py
query = (User.username == "vasya") | (User.username == "petya") | (User.username == "misha")
async for page in User.where(query):
    for user in page.items:
        print(user)
```

You can also represent the query like this:
```py
from detaorm import Or

query = Or(User.username == "vasya", User.username == "petya", User.username == "misha")
...
```

**Comment by mixartemev** [comment]
Yes, but `IN(array)` may contain about thousand values..

**Comment by circuitsacul** [comment]
I don't think that DetaBase supports that. The closest thing is `range`, which works for numerical fields only.

```py
await User.where(User.user_id.range([0, 500]))
```

**Comment by mixartemev** [comment]
Yea.. I got it:(
